language: rust
cache:
  cargo: true
  directories:
    - CMake
    - libwebm
rust:
  - nightly
script:

- sudo apt-get -qq update
- sudo apt-get install -y wget libvpx-dev

# Install newer cmake ~3.5 or above
- git clone https://github.com/Kitware/CMake || echo 'CMake already cloned'
- cd CMake
- cmake .
- make -j16
- cd ..

# Install libwebm
- git clone https://chromium.googlesource.com/webm/libwebm || echo 'libwebm already cloned'
- cd libwebm
- '../CMake/bin/cmake . -DENABLE_WEBM_PARSER=ON'
- make -j16
- sudo cp libwebm.a /usr/lib/
- sudo cp webm_parser/include/webm/ /usr/include/ -r
- cd ..

# Install catch for the C++ webm_parser_glue tests
- sudo wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -P /usr/include/

# Test C++ glue 
- (cd webm_parser_glue && ./build_test.sh && ./webm_parser_glue_test)

# Test Project
- cargo test