language: rust
cache:
  cargo: true
  directories:
    - CMake
    - libwebm
    - libvpx
rust:
  - nightly
script:
- sudo apt-get update -q
- sudo apt-get install -y yasm

# Install newer cmake ~3.5 or above
- git clone https://github.com/Kitware/CMake || echo 'CMake already cloned'
- cd CMake
- git pull
- cmake .
- make -j4
- cd ..

# Install libvpx
- git clone https://chromium.googlesource.com/webm/libvpx || echo 'libvpx already cloned'
- cd libvpx
- git pull
- ./configure --disable-examples --disable-docs --enable-shared --disable-static
- make -j4
- sudo cp libvpx.so* /usr/lib
- sudo make install
- cd ..

# Install libwebm
- git clone https://chromium.googlesource.com/webm/libwebm || echo 'libwebm already cloned'
- cd libwebm
- git pull
- ../CMake/bin/cmake . -DENABLE_WEBM_PARSER:BOOL=ON
- make -j4
- sudo cp libwebm.a /usr/lib/
- sudo cp webm_parser/include/webm/ /usr/include/ -r
- cd ..

# Install catch for the C++ webm_parser_glue tests
- sudo wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -P /usr/include/

# Test C++ glue 
- (cd webm_parser_glue && ./build_test.sh && ./webm_parser_glue_test)

# Test Project
- cargo test