language: rust
rust:
  - nightly
script:

- sudo apt-get -qq update
- sudo apt-get install -y wget libvpx-dev cmake clang gcc

# Install libwebm
- git clone https://chromium.googlesource.com/webm/libwebm
- cd libwebm
- cmake . -DENABLE_WEBM_PARSER:BOOL=ON
- make -j16
- sudo cp libwebm.a /usr/lib/
- sudo cp webm_parser/include/webm/ /usr/include/ -r

# Install catch for the C++ webm_parser_glue tests
- sudo wget https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp -o /usr/include/catch.hpp

# Test C++ glue
- (cd webm_parser_glue && ./build_test.sh && ./webm_parser_glue_test)

# Test Project
- cargo test